---
title: "usage"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{usage}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Main feature includes

  - control for covariates with `covariatesvar`, choose estimator with `control_type` 
  - get aggregated parameters with `result_type`
  - get clustered standard errors with `clustervar`
  
You can control for covariates by providing the name of the data columns (`x, x2`), and choose the method via the `control_type` argument among doubly-robust (`"dr"`), inverse probability weight (`"ipw"`), and outcome regression (`"or"`). Ex: `fastdid(..., control_type = "dr", covaraitesvar = c("x", "x2"))`. 

Clustered standard error can be obtained from multiplier bootstrap. Ex: `fastdid(..., boot = TRUE, clustervar = "x")`. 

Estimation for multiple outcomes can be done in one call by providing a vector of outcome column names. This saves a lot of time when using `ipw` since logit estimates can be recycled across outcomes. Ex: `fastdid(...,outcomevar = c("y", "y2"))`.
