require(data.table)
require(tidyverse)
require(fixest)
require(Hmisc)
require(lfe)
require(rlist)
require(car)
require(kit)
require(collapse)
require(fastmatch)
require(dreamerr)
require(future.apply)

plan(multisession)
setDTthreads(0)
options(kit.nThread = getDTthreads())
setFixest_nthreads(getDTthreads())
